apiVersion: v1 
kind: Pod 
metadata:
  name: busybox 
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: bitnami/kubectl:latest
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
    securityContext:
          privileged: true

